from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from nodecanon.adapters.base import BaseAdapter
from nodecanon.core.models import KGEdge, KGGraph, KGNode

# Characters that are not valid in Cypher labels or relationship types.
_INVALID_LABEL_RE = re.compile(r"[^A-Za-z0-9_]")


def _safe_label(text: str) -> str:
    """Convert a type string to a valid Cypher label (no spaces, special chars)."""
    cleaned = _INVALID_LABEL_RE.sub("_", text.strip())
    # Labels cannot start with a digit.
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned or "ENTITY"


def _cypher_str(value: Any) -> str:
    """Render a Python value as a Cypher literal."""
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_cypher_str(v) for v in value) + "]"
    # Fallback: JSON-encode then quote
    escaped = json.dumps(value).replace("'", "\\'")
    return f"'{escaped}'"


def _props_map(props: dict[str, Any]) -> str:
    """Render a dict as a Cypher properties map literal: {key: value, ...}"""
    if not props:
        return ""
    items = ", ".join(f"{k}: {_cypher_str(v)}" for k, v in sorted(props.items()))
    return "{" + items + "}"


class Neo4jAdapter(BaseAdapter):
    """Export-only adapter: write a resolved KGGraph as Cypher CREATE statements.

    Usage::

        from nodecanon.adapters.neo4j import Neo4jAdapter

        cypher = Neo4jAdapter().to_cypher(resolved_graph)
        Path("resolved.cypher").write_text(cypher)

    Then in Neo4j Browser or ``cypher-shell``::

        :source resolved.cypher
    """

    def load(self, source: Path | str | Any) -> KGGraph:
        raise NotImplementedError(
            "Neo4jAdapter is export-only. "
            "To read from a live Neo4j instance, use the official neo4j Python driver."
        )

    def dump(self, graph: KGGraph, destination: Path | str | Any) -> None:
        """Write Cypher to *destination* (a file path or a dict/object)."""
        cypher = self.to_cypher(graph)
        dest = Path(destination) if isinstance(destination, str) else destination
        if isinstance(dest, Path):
            dest.write_text(cypher, encoding="utf-8")
        elif isinstance(destination, dict):
            destination["cypher"] = cypher
        else:
            destination.cypher = cypher

    def to_cypher(self, graph: KGGraph) -> str:
        """Return a Cypher script that recreates *graph* in Neo4j.

        Uses MERGE on node id to make the script idempotent — running it twice
        will not create duplicate nodes.

        Node labels are derived from KGNode.type.  If type is None, the label
        ``Entity`` is used.  All KGNode fields (name, description, attributes,
        provenance) are stored as node properties.

        Relationship types are derived from KGEdge.relation.
        """
        lines: list[str] = [
            "// Generated by nodecanon — https://github.com/nodecanon/nodecanon",
            "// Run in Neo4j Browser or cypher-shell",
            "",
        ]

        for node in graph.nodes:
            lines.append(self._node_statement(node))

        if graph.nodes and graph.edges:
            lines.append("")

        for edge in graph.edges:
            lines.append(self._edge_statement(edge))

        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _node_props(node: KGNode) -> dict[str, Any]:
        props: dict[str, Any] = {"id": node.id, "name": node.name}
        if node.type is not None:
            props["type"] = node.type
        if node.description is not None:
            props["description"] = node.description
        if node.source_chunks:
            props["source_chunks"] = node.source_chunks
        if node._merged_from is not None:
            props["_merged_from"] = node._merged_from
        if node._merge_strategy is not None:
            props["_merge_strategy"] = node._merge_strategy
        if node._resolved_types is not None:
            props["_resolved_types"] = node._resolved_types
        props.update(node.attributes)
        return props

    def _node_statement(self, node: KGNode) -> str:
        label = _safe_label(node.type or "Entity")
        props = self._node_props(node)
        return f"MERGE (n:{label} {{id: {_cypher_str(node.id)}}}) SET n += {_props_map(props)};"

    @staticmethod
    def _edge_statement(edge: KGEdge) -> str:
        rel_type = _safe_label(edge.relation)
        edge_props: dict[str, Any] = {"weight": edge.weight}
        edge_props.update(edge.attributes)
        props_str = (" " + _props_map(edge_props)) if edge_props else ""
        return (
            f"MATCH (a {{id: {_cypher_str(edge.source_id)}}}), "
            f"(b {{id: {_cypher_str(edge.target_id)}}}) "
            f"MERGE (a)-[:{rel_type}{props_str}]->(b);"
        )


def to_cypher(graph: KGGraph) -> str:
    """Module-level convenience wrapper for Neo4jAdapter().to_cypher(graph)."""
    return Neo4jAdapter().to_cypher(graph)
